<?php
/**
* DirectMVC: A clean and to the point MVC framework
* 
* @author Ruben K. <ruben@directdevelopment.nl>
* @version 0.1
* @package DirectMVC
*/

/**
* WelcomeController class
* 
* This is the example controller to demonstrate how
* basic controllers work
* 
* @package Controllers
* @version 0.1
* @author Ruben K. <ruben@directdevelopment.nl>
*/
class WelcomeController extends Df_Controller
{
	/**
	* Index: The index method
	* 
	* @param Df_Request $request The framework request object
	* @return string The output generated by this controller
	*/
	public function Index( Df_Request $request )
	{
		$tpl = $this->view( 'welcome.html' );
		return $tpl->render( array(
			'name' => 'Ruben'
		));
	}
	
	public function Read( Df_Request $request, $id )
	{
		$this->_forwardIf( ( $request->getGetParameter( 'new-id' ) == 2 ), 'welcome_redirect', array(
			'id' => $request->getGetParameter( 'id' )
		) );	
		
		echo $id;
	}
	
	public function Read_new( Df_Request $request, $id )
	{
		echo 'New: ' . $id;
	}
}
